# FROM php:8.3-apache

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     git unzip zip \
#     libicu-dev libzip-dev libpq-dev \
#     && rm -rf /var/lib/apt/lists/*

#     # && docker-php-ext-install intl pdo pdo_mysql pdo_pgsql zip opcache

# COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# RUN a2enmod rewrite

# COPY . /var/www/html

# WORKDIR /var/www/html

# RUN composer create-project symfony/skeleton:"7.3.x" my_project_directory
# # RUN composer install --no-interaction --optimize-autoloader --no-dev

# RUN chown -R www-data:www-data var vendor

# EXPOSE 80

# CMD ["apache2-foreground"]

FROM php:8.3-alpine

ENV APP_DIR=/app \
    APP_ENV=dev \
    APP_DEBUG=1 \
    COMPOSER_ALLOW_SUPERUSER=1

WORKDIR ${APP_DIR}

# RUN apk add --no-cache git unzip icu-dev libzip-dev oniguruma-dev bash \
#     && docker-php-ext-install intl pdo_mysql zip opcache \
#     && pecl install apcu \
#     && docker-php-ext-enable apcu opcache


#################################################
# Dépendances runtime légères
# (icu-libs, libzip, zlib pour faire tourner intl/zip compilées)
RUN set -eux; \
    apk add --no-cache \
      git unzip bash \
      icu-libs libzip zlib

# Dépendances de build + extensions PHP + APCu, puis cleanup
RUN set -eux; \
    apk add --no-cache --virtual .build-deps \
      $PHPIZE_DEPS \
      icu-dev libzip-dev zlib-dev \
    ; \
    docker-php-ext-install \
      intl \
      pdo_mysql \
      zip \
      opcache \
    ; \
    pecl install apcu \
    && docker-php-ext-enable apcu opcache \
    ; \
    apk del .build-deps
#################################################

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copie (optionnelle) des fichiers si vous avez déjà un projet
# Si vous partez d'un dossier vide, laissez tel quel.
# COPY . ${APP_DIR}

COPY --chmod=755 docker-entrypoint.sh /usr/local/bin/docker-entrypoint.s    
ENTRYPOINT ["docker-entrypoint.sh"]

# Port du serveur PHP
EXPOSE 8000

# Commande par défaut : serveur PHP intégré
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]