name: Docker Image CI

on: 
  push:
    branches: [ "main" ]
    tags: "v*"
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:
    runs-on: ubuntu-latest

    steps:
      # - name: install front dependencies
      #   run: |
      #     cd ./frontend/salle-vation-front/ | npm i
      - name: install back dependencies
        run: |
          cd ./backend/salle_vation/ | composer i

  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --generate-notes

    
